language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
deploy:
  provider: surge
  skip_cleanup: true
  domain: alex-portfolio-data.surge.sh
  project: ./json/
on:
  branch: master
